/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { JevCredentialStatus, JevFeatureView, JevProbeResult, JevRecordDetail, JevRecordFilter, JevRecordPage } from '@dsh-jev/plugin/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6a6576 {
    getCredentialStatus: () => Promise<RemoteResult<JevCredentialStatus>>
    getRecord: (id: string) => Promise<RemoteResult<JevRecordDetail | null>>
    listFeatures: () => Promise<RemoteResult<JevFeatureView[]>>
    listRecords: (filter: JevRecordFilter) => Promise<RemoteResult<JevRecordPage>>
    setCredential: (value: string) => Promise<RemoteResult<JevCredentialStatus>>
    testConnection: (signal?: AbortSignal) => Promise<RemoteResult<JevProbeResult>>
  }
  interface TypertRemoteMap {
    'jev/getCredentialStatus': () => Promise<RemoteResult<JevCredentialStatus>>
    'jev/getRecord': (id: string) => Promise<RemoteResult<JevRecordDetail | null>>
    'jev/listFeatures': () => Promise<RemoteResult<JevFeatureView[]>>
    'jev/listRecords': (filter: JevRecordFilter) => Promise<RemoteResult<JevRecordPage>>
    'jev/setCredential': (value: string) => Promise<RemoteResult<JevCredentialStatus>>
    'jev/testConnection': (signal?: AbortSignal) => Promise<RemoteResult<JevProbeResult>>
  }
  interface TypertRemoteNamespaceMap {
    'jev': TypertRemoteNamespace$6a6576
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
