/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let JsonRemoteCodec$schema$value
const JsonRemoteCodec$schema = () => (JsonRemoteCodec$schema$value ??= z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]))
let _dsh_jev_plugin_jev_getCredentialStatus_result$schema$value
const _dsh_jev_plugin_jev_getCredentialStatus_result$schema = () => (_dsh_jev_plugin_jev_getCredentialStatus_result$schema$value ??= z.object({
  'configured': z.boolean(),
  'writable': z.boolean(),
  'source': z.union([z.undefined(), z.string()]).optional(),
}))
let _dsh_jev_plugin_jev_getRecord_parameter_0$schema$value
const _dsh_jev_plugin_jev_getRecord_parameter_0$schema = () => (_dsh_jev_plugin_jev_getRecord_parameter_0$schema$value ??= z.string())
let _dsh_jev_plugin_jev_getRecord_result$schema$value
const _dsh_jev_plugin_jev_getRecord_result$schema = () => (_dsh_jev_plugin_jev_getRecord_result$schema$value ??= z.union([z.literal(null), z.object({
  'link': z.object({
  'sessionId': z.union([z.undefined(), z.string()]).optional(),
  'runId': z.union([z.undefined(), z.string()]).optional(),
  'stepId': z.union([z.undefined(), z.string()]).optional(),
  'inputVersion': z.union([z.undefined(), z.string()]).optional(),
}),
  'attemptRecords': z.array(z.object({
  'id': z.string(),
  'startedAt': z.string(),
  'settledAt': z.union([z.undefined(), z.string()]).optional(),
  'latencyMs': z.union([z.undefined(), z.number()]).optional(),
  'connection': z.object({
  'baseUrl': z.string(),
  'model': z.string(),
  'credentialRef': z.string(),
}),
  'request': z.object({
  'state': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]),
  'questions': z.array(z.union([z.object({
  'id': z.string(),
  'kind': z.literal("choice"),
  'prompt': z.union([z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()]),
  'options': z.array(z.object({
  'id': z.string(),
  'description': z.union([z.literal(null), z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()]),
})),
}), z.object({
  'id': z.string(),
  'kind': z.literal("score"),
  'prompt': z.union([z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()]),
  'levels': z.array(z.union([z.literal(null), z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()])),
}), z.object({
  'id': z.string(),
  'kind': z.literal("noul"),
  'prompt': z.union([z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()]),
  'criteria': z.union([z.undefined(), z.object({
  'true': z.union([z.undefined(), z.literal(null), z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()]).optional(),
  'false': z.union([z.undefined(), z.literal(null), z.string(), z.array(z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])), z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()])).readonly()]).optional(),
})]).optional(),
})])),
}),
  'status': z.union([z.literal("pending"), z.literal("waiting"), z.literal("succeeded"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]),
  'rawResponse': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]).optional(),
  'response': z.union([z.undefined(), z.object({
  'answers': z.array(z.union([z.object({
  'id': z.string(),
  'kind': z.literal("choice"),
  'optionId': z.string(),
  'probabilities': z.union([z.undefined(), z.record(z.string(), z.number())]).optional(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'legend': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]).optional(),
}), z.object({
  'id': z.string(),
  'kind': z.literal("score"),
  'value': z.number(),
  'probabilities': z.union([z.undefined(), z.record(z.string(), z.number())]).optional(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'legend': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]).optional(),
}), z.object({
  'id': z.string(),
  'kind': z.literal("noul"),
  'probability': z.number(),
  'confidence': z.union([z.undefined(), z.number()]).optional(),
  'legend': z.union([z.undefined(), z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonRemoteCodec$schema())), z.record(z.string(), z.lazy(() => JsonRemoteCodec$schema())).readonly()]).optional(),
})])),
})]).optional(),
  'interpretation': z.union([z.undefined(), z.object({
  'usable': z.boolean(),
  'reason': z.union([z.undefined(), z.string()]).optional(),
})]).optional(),
  'failure': z.union([z.undefined(), z.object({
  'code': z.string(),
  'message': z.string(),
})]).optional(),
  'usage': z.union([z.undefined(), z.object({
  'inputTokens': z.union([z.undefined(), z.number()]).optional(),
  'outputTokens': z.union([z.undefined(), z.number()]).optional(),
})]).optional(),
})),
  'receipts': z.array(z.object({
  'id': z.string(),
  'status': z.union([z.literal("cancelled"), z.literal("unconfirmed"), z.literal("not-adopted"), z.literal("executed"), z.literal("execution-failed"), z.literal("observed")]),
  'reason': z.union([z.undefined(), z.string()]).optional(),
  'at': z.string(),
})),
  'failure': z.union([z.undefined(), z.object({
  'code': z.string(),
  'message': z.string(),
})]).optional(),
  'id': z.string(),
  'featureId': z.string(),
  'sessionId': z.union([z.undefined(), z.string()]).optional(),
  'status': z.union([z.literal("pending"), z.literal("waiting"), z.literal("succeeded"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]),
  'startedAt': z.string(),
  'updatedAt': z.string(),
  'attempts': z.number(),
  'actionStatus': z.union([z.undefined(), z.literal("cancelled"), z.literal("unconfirmed"), z.literal("not-adopted"), z.literal("executed"), z.literal("execution-failed"), z.literal("observed")]).optional(),
  'diagnostic': z.boolean(),
})]))
let _dsh_jev_plugin_jev_listFeatures_result$schema$value
const _dsh_jev_plugin_jev_listFeatures_result$schema = () => (_dsh_jev_plugin_jev_listFeatures_result$schema$value ??= z.array(z.object({
  'enabled': z.boolean(),
  'id': z.string(),
  'name': z.string(),
  'description': z.string(),
  'settingsDescription': z.union([z.undefined(), z.string()]).optional(),
})))
let _dsh_jev_plugin_jev_listRecords_parameter_0$schema$value
const _dsh_jev_plugin_jev_listRecords_parameter_0$schema = () => (_dsh_jev_plugin_jev_listRecords_parameter_0$schema$value ??= z.object({
  'featureId': z.union([z.undefined(), z.string()]).optional(),
  'status': z.union([z.undefined(), z.literal("pending"), z.literal("waiting"), z.literal("succeeded"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).optional(),
  'sessionId': z.union([z.undefined(), z.string()]).optional(),
  'cursor': z.union([z.undefined(), z.string()]).optional(),
  'limit': z.union([z.undefined(), z.number()]).optional(),
}))
let _dsh_jev_plugin_jev_listRecords_result$schema$value
const _dsh_jev_plugin_jev_listRecords_result$schema = () => (_dsh_jev_plugin_jev_listRecords_result$schema$value ??= z.object({
  'items': z.array(z.object({
  'id': z.string(),
  'featureId': z.string(),
  'sessionId': z.union([z.undefined(), z.string()]).optional(),
  'status': z.union([z.literal("pending"), z.literal("waiting"), z.literal("succeeded"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]),
  'startedAt': z.string(),
  'updatedAt': z.string(),
  'attempts': z.number(),
  'actionStatus': z.union([z.undefined(), z.literal("cancelled"), z.literal("unconfirmed"), z.literal("not-adopted"), z.literal("executed"), z.literal("execution-failed"), z.literal("observed")]).optional(),
  'diagnostic': z.boolean(),
})),
  'nextCursor': z.union([z.undefined(), z.string()]).optional(),
}))
let _dsh_jev_plugin_jev_setCredential_parameter_0$schema$value
const _dsh_jev_plugin_jev_setCredential_parameter_0$schema = () => (_dsh_jev_plugin_jev_setCredential_parameter_0$schema$value ??= z.string())
let _dsh_jev_plugin_jev_setCredential_result$schema$value
const _dsh_jev_plugin_jev_setCredential_result$schema = () => (_dsh_jev_plugin_jev_setCredential_result$schema$value ??= z.object({
  'configured': z.boolean(),
  'writable': z.boolean(),
  'source': z.union([z.undefined(), z.string()]).optional(),
}))
let _dsh_jev_plugin_jev_testConnection_result$schema$value
const _dsh_jev_plugin_jev_testConnection_result$schema = () => (_dsh_jev_plugin_jev_testConnection_result$schema$value ??= z.object({
  'ok': z.boolean(),
  'latencyMs': z.number(),
  'recordId': z.string(),
  'failure': z.union([z.undefined(), z.object({
  'code': z.string(),
  'message': z.string(),
})]).optional(),
}))

export const TYPERT = {
  package: '@dsh-jev/plugin',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@dsh-jev/plugin#jev/getCredentialStatus',
      service: 'jev',
      namespace: 'jev',
      method: 'getCredentialStatus',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin/types#JevCredentialStatus',
        create: _dsh_jev_plugin_jev_getCredentialStatus_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":174,"column":9},
    },
    {
      id: '@dsh-jev/plugin#jev/getRecord',
      service: 'jev',
      namespace: 'jev',
      method: 'getRecord',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin#jev/getRecord:id',
            create: _dsh_jev_plugin_jev_getRecord_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin#jev/getRecord:result',
        create: _dsh_jev_plugin_jev_getRecord_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":170,"column":9},
    },
    {
      id: '@dsh-jev/plugin#jev/listFeatures',
      service: 'jev',
      namespace: 'jev',
      method: 'listFeatures',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin#jev/listFeatures:result',
        create: _dsh_jev_plugin_jev_listFeatures_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":154,"column":9},
    },
    {
      id: '@dsh-jev/plugin#jev/listRecords',
      service: 'jev',
      namespace: 'jev',
      method: 'listRecords',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'filter',
          wire: 'filter',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin/types#JevRecordFilter',
            create: _dsh_jev_plugin_jev_listRecords_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin/types#JevRecordPage',
        create: _dsh_jev_plugin_jev_listRecords_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":161,"column":9},
    },
    {
      id: '@dsh-jev/plugin#jev/setCredential',
      service: 'jev',
      namespace: 'jev',
      method: 'setCredential',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'value',
          wire: 'value',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-jev/plugin#jev/setCredential:value',
            create: _dsh_jev_plugin_jev_setCredential_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin/types#JevCredentialStatus',
        create: _dsh_jev_plugin_jev_setCredential_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":181,"column":9},
    },
    {
      id: '@dsh-jev/plugin#jev/testConnection',
      service: 'jev',
      namespace: 'jev',
      method: 'testConnection',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-jev/plugin/types#JevProbeResult',
        create: _dsh_jev_plugin_jev_testConnection_result$schema,
      },
      sourceLocation: {"file":"packages/jev/src/index.ts","line":189,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "One profile's public judgment service and browser Remote namespace.",
        "summary": "One profile's public judgment service and browser Remote namespace.",
        "tags": [],
        "jsDoc": "/** One profile's public judgment service and browser Remote namespace. */",
        "key": "jev",
        "exportName": "JevService",
        "members": [
          {
            "kind": "method",
            "name": "registerFeature",
            "signature": "registerFeature(feature: JevFeatureDefinition): () => void",
            "summary": "Register a consumer feature for this Host lifetime; the caller owns the disposer.",
            "jsDoc": "/** Register a consumer feature for this Host lifetime; the caller owns the disposer. */"
          },
          {
            "kind": "method",
            "name": "listFeatures",
            "signature": "@Remote('listFeatures') async listFeatures(): Promise<JevFeatureView[]>",
            "summary": "Current registrations, with unknown and newly registered ids disabled by default.",
            "jsDoc": "/** Current registrations, with unknown and newly registered ids disabled by default. */"
          },
          {
            "kind": "method",
            "name": "listRecords",
            "signature": "@Remote('listRecords') async listRecords(filter: JevRecordFilter): Promise<JevRecordPage>",
            "summary": "Query only the current profile, with bounded page size and optional filters.",
            "jsDoc": "/** Query only the current profile, with bounded page size and optional filters. */"
          },
          {
            "kind": "method",
            "name": "getRecord",
            "signature": "@Remote('getRecord') async getRecord(id: string): Promise<JevRecordDetail | null>",
            "summary": "Read one current-profile operation after the list has identified it.",
            "jsDoc": "/** Read one current-profile operation after the list has identified it. */"
          },
          {
            "kind": "method",
            "name": "getCredentialStatus",
            "signature": "@Remote('getCredentialStatus') async getCredentialStatus(): Promise<JevCredentialStatus>",
            "summary": "Report credential presence, source, and writability without its value.",
            "jsDoc": "/** Report credential presence, source, and writability without its value. */"
          },
          {
            "kind": "method",
            "name": "setCredential",
            "signature": "@Remote('setCredential') async setCredential(value: string): Promise<JevCredentialStatus>",
            "summary": "Save or replace the current profile's configured credential reference.",
            "jsDoc": "/** Save or replace the current profile's configured credential reference. */"
          },
          {
            "kind": "method",
            "name": "testConnection",
            "signature": "@Remote('testConnection') async testConnection(signal: AbortSignal): Promise<JevProbeResult>",
            "summary": "Run one fixed diagnostic without a business feature or user state.",
            "jsDoc": "/** Run one fixed diagnostic without a business feature or user state. */"
          },
          {
            "kind": "method",
            "name": "judge",
            "signature": "judge(options: JevJudgeOptions): Promise<JevJudgeResult>",
            "summary": "Judge one dependent operation; only a human retry invokes `refresh` again.",
            "jsDoc": "/** Judge one dependent operation; only a human retry invokes `refresh` again. */"
          },
          {
            "kind": "method",
            "name": "judgeOnce",
            "signature": "judgeOnce(options: JevJudgeOptions): Promise<JevJudgeOnceResult>",
            "summary": "Make one logged attempt without human waiting or automatic retry.",
            "jsDoc": "/** Make one logged attempt without human waiting or automatic retry. Only `ok` permits adoption. */"
          },
          {
            "kind": "method",
            "name": "isFeatureEnabled",
            "signature": "isFeatureEnabled(featureId: string): boolean",
            "summary": "Read this profile's current enablement synchronously; absent feature ids are disabled.",
            "jsDoc": "/** Read this profile's current enablement synchronously; absent feature ids are disabled. */"
          },
          {
            "kind": "method",
            "name": "onFeatureStateChange",
            "signature": "onFeatureStateChange(listener: (features: Readonly<Record<string, boolean>>) => void): () => void",
            "summary": "Observe committed feature-setting changes synchronously; the consumer owns the disposer.",
            "jsDoc": "/** Observe committed feature-setting changes synchronously; the consumer owns the disposer. */"
          },
          {
            "kind": "method",
            "name": "recordInterrupted",
            "signature": "recordInterrupted(featureId: string, link: JevOperationLink): Promise<JevRecordDetail>",
            "summary": "Record interrupted input without a model call, human question, or attempt; stable message links are idempotent.",
            "jsDoc": "/** Record interrupted input without a model call, human question, or attempt; stable message links are idempotent. */"
          },
          {
            "kind": "method",
            "name": "writeReceipt",
            "signature": "async writeReceipt(operationId: string, receipt: JevActionReceipt): Promise<JevRecordDetail>",
            "summary": "Persist one action receipt; a failed write leaves execution status unconfirmed.",
            "jsDoc": "/** Persist one action receipt; a failed write leaves execution status unconfirmed. */"
          }
        ],
        "types": [
          {
            "name": "JevActionReceipt",
            "declaration": "export interface JevActionReceipt {\n    id: string;\n    status: JevActionStatus;\n    reason?: string;\n    at: string;\n}"
          },
          {
            "name": "JevActionStatus",
            "declaration": "export type JevActionStatus = 'unconfirmed' | 'not-adopted' | 'cancelled' | 'executed' | 'execution-failed' | 'observed';"
          },
          {
            "name": "JevAnswer",
            "declaration": "export type JevAnswer = { id: string; kind: 'choice'; optionId: string; probabilities?: Record<string, number>; confidence?: number; legend?: Json; } | { id: string; kind: 'score'; value: number; probabilities?: Record<string, number>; confidence?: number; legend?: Json; } | { id: string; kind: 'noul'; probability: number; confidence?: number; legend?: Json; };"
          },
          {
            "name": "JevAttemptRecord",
            "declaration": "export interface JevAttemptRecord {\n    id: string;\n    startedAt: string;\n    settledAt?: string;\n    latencyMs?: number;\n    connection: { baseUrl: string; model: string; credentialRef: string; };\n    request: JevRequest;\n    status: JevRecordStatus;\n    rawResponse?: Json;\n    response?: JevResponse;\n    interpretation?: { usable: boolean; reason?: string; };\n    failure?: { code: string; message: string; };\n    usage?: { inputTokens?: number; outputTokens?: number; };\n}"
          },
          {
            "name": "JevCredentialStatus",
            "declaration": "export interface JevCredentialStatus {\n    configured: boolean;\n    writable: boolean;\n    source?: string;\n}"
          },
          {
            "name": "JevFeatureDefinition",
            "declaration": "export interface JevFeatureDefinition {\n    id: string;\n    name: string;\n    description: string;\n    settingsDescription?: string;\n}"
          },
          {
            "name": "JevFeatureView",
            "declaration": "export interface JevFeatureView extends JevFeatureDefinition {\n    enabled: boolean;\n}"
          },
          {
            "name": "JevInput",
            "declaration": "export type JevInput = string | readonly Json[] | { readonly [key: string]: Json; };"
          },
          {
            "name": "JevJudgeOnceResult",
            "declaration": "export type JevJudgeOnceResult = JevJudgeResult | { kind: 'failed'; operationId?: string; failure: { code: string; message: string; }; };"
          },
          {
            "name": "JevJudgeOptions",
            "declaration": "export interface JevJudgeOptions {\n    featureId: string;\n    link: JevOperationLink;\n    agent: Agent;\n    refresh: (signal: AbortSignal) => JevRequest | Promise<JevRequest>;\n    interpret?: (response: JevResponse, signal: AbortSignal) => { usable: true; } | { usable: false; reason: string; } | Promise<{ usable: true; } | { usable: false; reason: string; }>;\n    canAdopt?: (response: JevResponse, signal: AbortSignal) => true | string | Promise<true | string>;\n    signal?: AbortSignal;\n}"
          },
          {
            "name": "JevJudgeResult",
            "declaration": "export type JevJudgeResult = { kind: 'ok'; operationId: string; attemptId: string; response: JevResponse; } | { kind: 'cancelled'; operationId: string; } | { kind: 'not-adopted'; operationId: string; reason: string; };"
          },
          {
            "name": "JevOperationLink",
            "declaration": "export interface JevOperationLink {\n    sessionId?: string;\n    runId?: string;\n    stepId?: string;\n    inputVersion?: string;\n}"
          },
          {
            "name": "JevProbeResult",
            "declaration": "export interface JevProbeResult {\n    ok: boolean;\n    latencyMs: number;\n    recordId: string;\n    failure?: { code: string; message: string; };\n}"
          },
          {
            "name": "JevQuestion",
            "declaration": "export type JevQuestion = { id: string; kind: 'choice'; prompt: JevInput; options: readonly { id: string; description: JevInput | null; }[]; } | { id: string; kind: 'score'; prompt: JevInput; levels: readonly (JevInput | null)[]; } | { id: string; kind: 'noul'; prompt: JevInput; criteria?: { true?: JevInput | null; false?: JevInput | null; }; };"
          },
          {
            "name": "JevRecordDetail",
            "declaration": "export interface JevRecordDetail extends JevRecordSummary {\n    link: JevOperationLink;\n    attemptRecords: readonly JevAttemptRecord[];\n    receipts: readonly JevActionReceipt[];\n    failure?: { code: string; message: string; };\n}"
          },
          {
            "name": "JevRecordFilter",
            "declaration": "export interface JevRecordFilter {\n    featureId?: string;\n    status?: JevRecordStatus;\n    sessionId?: string;\n    cursor?: string;\n    limit?: number;\n}"
          },
          {
            "name": "JevRecordPage",
            "declaration": "export interface JevRecordPage {\n    items: readonly JevRecordSummary[];\n    nextCursor?: string;\n}"
          },
          {
            "name": "JevRecordStatus",
            "declaration": "export type JevRecordStatus = 'pending' | 'waiting' | 'succeeded' | 'failed' | 'cancelled' | 'interrupted';"
          },
          {
            "name": "JevRecordSummary",
            "declaration": "export interface JevRecordSummary {\n    id: string;\n    featureId: string;\n    sessionId?: string;\n    status: JevRecordStatus;\n    startedAt: string;\n    updatedAt: string;\n    attempts: number;\n    actionStatus?: JevActionStatus;\n    diagnostic: boolean;\n}"
          },
          {
            "name": "JevRequest",
            "declaration": "export interface JevRequest {\n    state: Json;\n    questions: readonly JevQuestion[];\n}"
          },
          {
            "name": "JevResponse",
            "declaration": "export interface JevResponse {\n    answers: readonly JevAnswer[];\n}"
          },
          {
            "name": "Json",
            "declaration": "export type Json = null | boolean | number | string | readonly Json[] | { readonly [key: string]: Json; };"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
